### ISSUE TITLE
Package directory is missing

### ISSUE THREAD

**Issue by Ichmed** [Elektrobit/elos#2]
The README mentions a directory called `package` which does no longer exist, without its contents the source can not be built.

**Comment by gehwolf** [comment]
Hi Michael,

thanks for your report. Your are right the `package` directory mentioned in the README doesn't exists anymore. We should remove it to avoid confusion. 

Can you please provide some information about the build failure you get? We didn't expect any build dependencies to the `package` directory.

**Comment by Ichmed** [comment]
The directory apparently contained a file called `elos.spec` which was used for packaging. As-is the package no longer builds.

**Comment by gehwolf** [comment]
We removed the files in `package` during the open source process from elos as they are very specific and may contain details that are not generally applicable. I am afraid  you need to maintain the spec file in your packaging process or system.

 Maybe you are looking for this https://github.com/Elektrobit/system-config/tree/master/config-system-elos ? As far as I can tell, these configuration files are originally derived from those maintained in the `packages` folder and already used by some build system.

Please let me know if this has helped you.
